# build a minimal interpreter
COPT = -Os -DNDEBUG

PROG = pycopy-minimal

#FROZEN_MANIFEST =
FROZEN_DIR =
FROZEN_MPY_DIR =

MICROPY_PY_BTREE = 0
MICROPY_PY_FFI = 0
MICROPY_PY_SOCKET = 0
MICROPY_PY_THREAD = 0
MICROPY_PY_TERMIOS = 0
MICROPY_PY_USSL = 0
MICROPY_USE_READLINE = 0
